# Generated by Django 4.1 on 2023-09-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('l_name', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
